from typing import List, Tuple

from aaa.tokenizer.models import TokenType

FIXED_SIZED_TOKENS: List[Tuple[str, TokenType]] = [
    ("-", TokenType.IDENTIFIER),
    (",", TokenType.COMMA),
    ("!", TokenType.SET_FIELD),
    ("!=", TokenType.IDENTIFIER),
    ("?", TokenType.GET_FIELD),
    (".", TokenType.IDENTIFIER),
    ("[", TokenType.TYPE_PARAM_BEGIN),
    ("]", TokenType.TYPE_PARAM_END),
    ("{", TokenType.BEGIN),
    ("}", TokenType.END),
    ("*", TokenType.IDENTIFIER),
    ("/", TokenType.IDENTIFIER),
    ("%", TokenType.IDENTIFIER),
    ("+", TokenType.IDENTIFIER),
    ("<", TokenType.IDENTIFIER),
    ("<=", TokenType.IDENTIFIER),
    ("=", TokenType.IDENTIFIER),
    (">", TokenType.IDENTIFIER),
    (">=", TokenType.IDENTIFIER),
    (":", TokenType.COLON),
    ("args", TokenType.ARGS),
    ("as", TokenType.AS),
    ("else", TokenType.ELSE),
    ("false", TokenType.FALSE),
    ("foreach", TokenType.FOREACH),
    ("fn", TokenType.FUNCTION),
    ("from", TokenType.FROM),
    ("if", TokenType.IF),
    ("import", TokenType.IMPORT),
    ("return", TokenType.RETURN),
    ("struct", TokenType.STRUCT),
    ("true", TokenType.TRUE),
    ("type", TokenType.TYPE),
    ("while", TokenType.WHILE),
]
