// Grammar for the
//
//    mm
//    ##    mmm    mmm
//   #  #  "   #  "   #
//   #mm#  m"""#  m"""#
//  #    # "mm"#  "mm"#
//
// language.

%import common.WS
%ignore WS

COMMENT: "//" /[^\n]*/ "\n"
%ignore COMMENT

SHEBANG: "#!" /[^\n]*/ "\n"
%ignore SHEBANG

integer: /(-)?[0-9]+/

%import common.ESCAPED_STRING
string: ESCAPED_STRING


// top-level block keywords
FN:         "fn"
_IMPORT:    "import"
STRUCT:     "struct"
TYPE:       "type"

// block delimiters
BEGIN:       "{"
_END:        "}"

// function keywords
_AS:         "as"
_ARGS:       "args"
_RETURN:     "return"

// struct operators
GET_FIELD:    "?"
SET_FIELD:    "!"

// control flow keywords
ELSE:        "else"
FROM:        "from"
IF:          "if"
WHILE:       "while"

// keywords for builtin constants
FALSE:       "false"
TRUE:        "true"

// --- file roots ---

builtins_file_root: (function_declaration | type_declaration)+

regular_file_root: (function_definition | import_statement | struct_definition)+

// --- imports ---

import_statement: FROM string _IMPORT import_items

import_items: import_item ("," import_item)* [","]

import_item: identifier [_AS identifier]

// --- structs and types ---

type_declaration: TYPE flat_type_literal

struct_definition: STRUCT identifier BEGIN arguments _END

struct_field_query: string GET_FIELD

struct_field_update: string BEGIN function_body _END SET_FIELD

// --- functions, arguments, return types ---

function_declaration: FN function_name [_ARGS arguments] [_RETURN return_types]

function_definition: function_declaration BEGIN function_body _END

flat_type_literal: identifier [flat_type_params]

type_literal: identifier [type_params]

type_params: "[" type_literal ("," type_literal)* [","] "]"

flat_type_params: "[" identifier ("," identifier)* [","] "]"

function_name: flat_type_literal [":" identifier]

function_call: identifier ([type_params] | [":" identifier])

arguments: argument ("," argument)* [","]

argument: identifier _AS type_literal

return_types: type_literal ("," type_literal)* [","]

// --- literals ---

literal: boolean | integer | string

!boolean: TRUE | FALSE

// --- function body ---

function_body: function_body_item+

function_body_item: ( \
      literal
    | function_call
    | branch
    | loop
    | struct_field_query
    | struct_field_update \
)

// --- branch ---

branch: IF function_body BEGIN function_body _END [ELSE BEGIN function_body _END]

// --- loop ---

loop: WHILE function_body BEGIN function_body _END

// --- identifier ---

!identifier: /[a-zA-Z_]+/
           | "-"
           | "!="
           | "."
           | "*"
           | "/"
           | "%"
           | "+"
           | "<"
           | "<="
           | "="
           | ">"
           | ">="
