name: Python package

on: [push, pull_request]

jobs:
  build-python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.1
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1'
    - uses: pdm-project/setup-pdm@v3
      name: Setup PDM
      with:
        python-version: "3.12.1"         # Version range or exact version of a Python version to use, the same as actions/setup-python
        architecture: x64                # The target architecture (x86, x64) of the Python interpreter. the same as actions/setup-python
        version: head
        prerelease: false                # Allow prerelease versions of PDM to be installed
        enable-pep582: false             # Enable PEP 582 package loading globally
        allow-python-prereleases: false  # Allow prerelease versions of Python to be installed. For example if only 3.12-dev is available, 3.12 will fallback to 3.12-dev
    - name: Install dependencies
      run: pdm install
    - name: Run linters
      run:
        pdm add pre-commit &&
        pdm run pre-commit run --all-files
    - name: Run Python tests
      run: |
        pdm install --production
        export AAA_STDLIB_PATH=$(pwd)/stdlib
        pdm run pytest --color=yes --cov=aaa --cov-report=term-missing -x -vv
  build-rust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path rust/Cargo.toml

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path rust/Cargo.toml
