name: Build

on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always

jobs:
  build-rust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Run linters
        run: |
          pip install pre-commit
          pre-commit run --all-files
      - name: Build
        run: |
          export AAA_STDLIB_PATH=$(pwd)/stdlib
          cargo build --manifest-path aaa/Cargo.toml
      - name: Test
        run: |
          export AAA_STDLIB_PATH=$(pwd)/stdlib
          cargo test --manifest-path aaa/Cargo.toml
